# Projet de DataViz (S2)
## LACROIX Rémi, GOLOVAN Mykola, ARA ESPES Jorge
### Sujet - Artisans : nombre d'entreprises, chiffre d'affaires et valeur ajoutée

In [1]:
import pandas as pd
import xlrd

In [15]:
fichier_artisans = 'artisans_etalab.xls'
nombre_de_lignes = 103 # 103 car on commence à partir de la 3e ligne
colonne_alimentation = 6
colonne_fabrication = 7
colonne_batiment = 8
colonne_services = 9

dt = pd.read_excel(fichier_artisans, sheetname = 'Comptages', header = 2)
s = xlrd.open_workbook(fichier_artisans)
dt

# tableaux pour les valeurs finales
valeursMax = []
valeursMin = []

# tableaux pour les valeurs intermédiaire
valeurs_alimentation = []
valeurs_fabrication = []
valeurs_batiment = []
valeurs_services = []

with open(fichier_artisans, 'r') as f:
    for ligne in range(3, nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, colonne_alimentation).value
        valeurs_alimentation.append(valeur)

with open(fichier_artisans, 'r') as f:
    for ligne in range(3, nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, colonne_fabrication).value
        valeurs_fabrication.append(valeur)
        
with open(fichier_artisans, 'r') as f:
    for ligne in range(3, nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, colonne_batiment).value
        valeurs_batiment.append(valeur)

with open(fichier_artisans, 'r') as f:
    for ligne in range(3, nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, colonne_services).value
        valeurs_services.append(valeur)
        
        
#print(valeurs_alimentation)
#print(valeurs_fabrication)
#print(valeurs_batiment)
#print(valeurs_services)

meilleur_alimentation = max(valeurs_alimentation)
meilleur_fabrication = max(valeurs_fabrication)
meilleur_batiment = max(valeurs_batiment)
meilleur_services = max(valeurs_services)

print(meilleur_alimentation)
print(meilleur_fabrication)
print(meilleur_batiment)
print(meilleur_services)

for i in range(nombre_de_lignes-3):
    if valeurs_alimentation[i] == meilleur_alimentation:
        index_meilleur_alimentation = i
    if valeurs_fabrication[i] == meilleur_fabrication:
        index_meilleur_fabrication = i
    if valeurs_batiment[i] == meilleur_batiment:
        index_meilleur_batiment = i
    if valeurs_services[i] == meilleur_services:
        index_meilleur_services = i
        
print(index_meilleur_alimentation)
print(index_meilleur_batiment)
print(index_meilleur_fabrication)
print(index_meilleur_services)

2165.0
6232.0
15088.0
10431.0
4
4
4
4

In [3]:
dt

                                                                         1. ALIMENTATION  \
1.0  Guadeloupe                 971 Guadeloupe              11150 10108              674
2.0  Martinique                 972 Martinique              10032 9103               508
3.0  Guyane                     973 Guyane                  3977  3440               278
4.0  La Réunion                 974 La Réunion              14253 12010              871
11.0 Île-de-France              75  Paris                   41415 33916             2165
NaN  NaN                        77  Seine-et-Marne          20120 16925              918
                                78  Yvelines                17025 14395              895
                                91  Essonne                 17127 14070              864
                                92  Hauts-de-Seine          15322 12793              928
                                93  Seine-Saint-Denis       23098 19177             1084
                                94  Val-de-Marne            17601 14625              970
                                95  Val-d'Oise              16926 14249              773
21.0 Champagne-Ardenne          8   Ardennes                4201  3531               330
NaN  NaN                        10  Aube                    4721  3787               282
                                51  Marne                   7602  6177               605
                                52  Haute-Marne             2862  2273               206
22.0 Picardie                   2   Aisne                   6902  5757               513
NaN  NaN                        60  Oise                    10949 9285               636
                                80  Somme                   7643  5890               590
23.0 Haute-Normandie            27  Eure                    9814  8261               697
NaN  NaN                        76  Seine-Maritime          15261 12273             1382
24.0 Centre                     18  Cher                    5315  4268               401
NaN  NaN                        28  Eure-et-Loir            6781  5615               469
                                36  Indre                   3905  3131               356
                                37  Indre-et-Loire          9109  7533               677
                                41  Loir-et-Cher            5410  4503               436
                                45  Loiret                  8934  7791               581
25.0 Basse-Normandie            14  Calvados                10890 8873               901
NaN  NaN                        50  Manche                  7939  6249               864
                                61  Orne                    4927  3990               436
...                                                                                  ...
                                81  Tarn                    7873  6467               518
                                82  Tarn-et-Garonne         5008  4084               298
74.0 Limousin                   19  Corrèze                 5407  4172               388
NaN  NaN                        23  Creuse                  2505  1999               200
                                87  Haute-Vienne            6586  5198               441
82.0 Rhône-Alpes                1   Ain                     11768 9233               649
NaN  NaN                        7   Ardèche                 6910  5615               541
                                26  Drôme                   10922 8845               668
                                38  Isère                   22994 19058             1144
                                42  Loire                   12869 11076              921
                                69  Rhône                   28712 24148             1464
                                73  Savoie                  10624 8257               481
                                74  Haute-Savoie            15897 12771              695
83.0 Auvergne                   3   Allier                  5362  4551               426
NaN  NaN                        15  Cantal                  3103  2468               248
                                43  Haute-Loire             4692  3958               417
                                63  Puy-de-Dôme             10845 8972               739
91.0 Languedoc-Roussillon       11  Aude                    7239  5936               473
NaN  NaN                        30  Gard                    16174 13286              875
                                34  Hérault                 24323 18807             1229
                                48  Lozère                  1954  1501               181
                                66  Pyrénées-Orientales     10187 8015               537
93.0 Provence-Alpes-Côte d'Azur 4   Alpes-de-Haute-Provence 4127  3373               323
NaN  NaN                        5   Hautes-Alpes            3884  2815               245
                                6   Alpes-Maritimes         32362 26083             1225
                                13  Bouches-du-Rhône        35829 30283             2097
                                83  Var                     27931 22752             1312
                                84  Vaucluse                13559 11336              706
94.0 Corse                      2A  Corse-du-Sud            4453  3691               276
NaN  NaN                        2B  Haute-Corse             5202  4139               335

                                                                         2. FABRICATION  \
1.0  Guadeloupe                 971 Guadeloupe              11150 10108            1696
2.0  Martinique                 972 Martinique              10032 9103             1617
3.0  Guyane                     973 Guyane                  3977  3440              673
4.0  La Réunion                 974 La Réunion              14253 12010            2067
11.0 Île-de-France              75  Paris                   41415 33916            6232
NaN  NaN                        77  Seine-et-Marne          20120 16925            2026
                                78  Yvelines                17025 14395            1597
                                91  Essonne                 17127 14070            1421
                                92  Hauts-de-Seine          15322 12793            1298
                                93  Seine-Saint-Denis       23098 19177            1710
                                94  Val-de-Marne            17601 14625            1483
                                95  Val-d'Oise              16926 14249            1525
21.0 Champagne-Ardenne          8   Ardennes                4201  3531              552
NaN  NaN                        10  Aube                    4721  3787              578
                                51  Marne                   7602  6177              794
                                52  Haute-Marne             2862  2273              423
22.0 Picardie                   2   Aisne                   6902  5757              728
NaN  NaN                        60  Oise                    10949 9285             1080
                                80  Somme                   7643  5890              793
23.0 Haute-Normandie            27  Eure                    9814  8261             1055
NaN  NaN                        76  Seine-Maritime          15261 12273            1511
24.0 Centre                     18  Cher                    5315  4268              594
NaN  NaN                        28  Eure-et-Loir            6781  5615              785
                                36  Indre                   3905  3131              494
                                37  Indre-et-Loire          9109  7533             1146
                                41  Loir-et-Cher            5410  4503              663
                                45  Loiret                  8934  7791             1057
25.0 Basse-Normandie            14  Calvados                10890 8873             1000
NaN  NaN                        50  Manche                  7939  6249              794
                                61  Orne                    4927  3990              515
...                                                                                 ...
                                81  Tarn                    7873  6467             1165
                                82  Tarn-et-Garonne         5008  4084              516
74.0 Limousin                   19  Corrèze                 5407  4172              596
NaN  NaN                        23  Creuse                  2505  1999              261
                                87  Haute-Vienne            6586  5198              837
82.0 Rhône-Alpes                1   Ain                     11768 9233             1701
NaN  NaN                        7   Ardèche                 6910  5615              737
                                26  Drôme                   10922 8845             1357
                                38  Isère                   22994 19058            3059
                                42  Loire                   12869 11076            2019
                                69  Rhône                   28712 24148            3877
                                73  Savoie                  10624 8257             1130
                                74  Haute-Savoie            15897 12771            2106
83.0 Auvergne                   3   Allier                  5362  4551              616
NaN  NaN                        15  Cantal                  3103  2468              278
                                43  Haute-Loire             4692  3958              702
                                63  Puy-de-Dôme             10845 8972             1415
91.0 Languedoc-Roussillon       11  Aude                    7239  5936              629
NaN  NaN                        30  Gard                    16174 13286            1642
                                34  Hérault                 24323 18807            2033
                                48  Lozère                  1954  1501              210
                                66  Pyrénées-Orientales     10187 8015              856
93.0 Provence-Alpes-Côte d'Azur 4   Alpes-de-Haute-Provence 4127  3373              397
NaN  NaN                        5   Hautes-Alpes            3884  2815              353
                                6   Alpes-Maritimes         32362 26083            2927
                                13  Bouches-du-Rhône        35829 30283            3811
                                83  Var                     27931 22752            2498
                                84  Vaucluse                13559 11336            1530
94.0 Corse                      2A  Corse-du-Sud            4453  3691              381
NaN  NaN                        2B  Haute-Corse             5202  4139              427

                                                                         3. BATIMENT  \
1.0  Guadeloupe                 971 Guadeloupe              11150 10108         5549
2.0  Martinique                 972 Martinique              10032 9103          4497
3.0  Guyane                     973 Guyane                  3977  3440          1845
4.0  La Réunion                 974 La Réunion              14253 12010         5564
11.0 Île-de-France              75  Paris                   41415 33916        15088
NaN  NaN                        77  Seine-et-Marne          20120 16925         8323
                                78  Yvelines                17025 14395         6969
                                91  Essonne                 17127 14070         7326
                                92  Hauts-de-Seine          15322 12793         5618
                                93  Seine-Saint-Denis       23098 19177        10194
                                94  Val-de-Marne            17601 14625         7053
                                95  Val-d'Oise              16926 14249         7213
21.0 Champagne-Ardenne          8   Ardennes                4201  3531          1629
NaN  NaN                        10  Aube                    4721  3787          1835
                                51  Marne                   7602  6177          2918
                                52  Haute-Marne             2862  2273           971
22.0 Picardie                   2   Aisne                   6902  5757          2805
NaN  NaN                        60  Oise                    10949 9285          4636
                                80  Somme                   7643  5890          2668
23.0 Haute-Normandie            27  Eure                    9814  8261          4231
NaN  NaN                        76  Seine-Maritime          15261 12273         5314
24.0 Centre                     18  Cher                    5315  4268          2094
NaN  NaN                        28  Eure-et-Loir            6781  5615          2799
                                36  Indre                   3905  3131          1413
                                37  Indre-et-Loire          9109  7533          3506
                                41  Loir-et-Cher            5410  4503          2203
                                45  Loiret                  8934  7791          3934
25.0 Basse-Normandie            14  Calvados                10890 8873          4423
NaN  NaN                        50  Manche                  7939  6249          2924
                                61  Orne                    4927  3990          1984
...                                                                              ...
                                81  Tarn                    7873  6467          3096
                                82  Tarn-et-Garonne         5008  4084          2164
74.0 Limousin                   19  Corrèze                 5407  4172          2048
NaN  NaN                        23  Creuse                  2505  1999          1016
                                87  Haute-Vienne            6586  5198          2304
82.0 Rhône-Alpes                1   Ain                     11768 9233          4355
NaN  NaN                        7   Ardèche                 6910  5615          2885
                                26  Drôme                   10922 8845          4411
                                38  Isère                   22994 19058         9416
                                42  Loire                   12869 11076         4932
                                69  Rhône                   28712 24148        10986
                                73  Savoie                  10624 8257          4289
                                74  Haute-Savoie            15897 12771         6539
83.0 Auvergne                   3   Allier                  5362  4551          2163
NaN  NaN                        15  Cantal                  3103  2468          1262
                                43  Haute-Loire             4692  3958          1875
                                63  Puy-de-Dôme             10845 8972          4263
91.0 Languedoc-Roussillon       11  Aude                    7239  5936          3156
NaN  NaN                        30  Gard                    16174 13286         7167
                                34  Hérault                 24323 18807        10174
                                48  Lozère                  1954  1501           768
                                66  Pyrénées-Orientales     10187 8015          4273
93.0 Provence-Alpes-Côte d'Azur 4   Alpes-de-Haute-Provence 4127  3373          1787
NaN  NaN                        5   Hautes-Alpes            3884  2815          1476
                                6   Alpes-Maritimes         32362 26083        13890
                                13  Bouches-du-Rhône        35829 30283        14343
                                83  Var                     27931 22752        12941
                                84  Vaucluse                13559 11336         6121
94.0 Corse                      2A  Corse-du-Sud            4453  3691          2204
NaN  NaN                        2B  Haute-Corse             5202  4139          2408

                                                                         4. SERVICES
1.0  Guadeloupe                 971 Guadeloupe              11150 10108         2189
2.0  Martinique                 972 Martinique              10032 9103          2481
3.0  Guyane                     973 Guyane                  3977  3440           644
4.0  La Réunion                 974 La Réunion              14253 12010         3508
11.0 Île-de-France              75  Paris                   41415 33916        10431
NaN  NaN                        77  Seine-et-Marne          20120 16925         5658
                                78  Yvelines                17025 14395         4934
                                91  Essonne                 17127 14070         4459
                                92  Hauts-de-Seine          15322 12793         4949
                                93  Seine-Saint-Denis       23098 19177         6189
                                94  Val-de-Marne            17601 14625         5119
                                95  Val-d'Oise              16926 14249         4738
21.0 Champagne-Ardenne          8   Ardennes                4201  3531          1020
NaN  NaN                        10  Aube                    4721  3787          1092
                                51  Marne                   7602  6177          1860
                                52  Haute-Marne             2862  2273           673
22.0 Picardie                   2   Aisne                   6902  5757          1711
NaN  NaN                        60  Oise                    10949 9285          2933
                                80  Somme                   7643  5890          1839
23.0 Haute-Normandie            27  Eure                    9814  8261          2278
NaN  NaN                        76  Seine-Maritime          15261 12273         4066
24.0 Centre                     18  Cher                    5315  4268          1179
NaN  NaN                        28  Eure-et-Loir            6781  5615          1562
                                36  Indre                   3905  3131           868
                                37  Indre-et-Loire          9109  7533          2204
                                41  Loir-et-Cher            5410  4503          1201
                                45  Loiret                  8934  7791          2219
25.0 Basse-Normandie            14  Calvados                10890 8873          2549
NaN  NaN                        50  Manche                  7939  6249          1667
                                61  Orne                    4927  3990          1055
...                                                                              ...
                                81  Tarn                    7873  6467          1688
                                82  Tarn-et-Garonne         5008  4084          1106
74.0 Limousin                   19  Corrèze                 5407  4172          1140
NaN  NaN                        23  Creuse                  2505  1999           522
                                87  Haute-Vienne            6586  5198          1616
82.0 Rhône-Alpes                1   Ain                     11768 9233          2528
NaN  NaN                        7   Ardèche                 6910  5615          1452
                                26  Drôme                   10922 8845          2409
                                38  Isère                   22994 19058         5439
                                42  Loire                   12869 11076         3204
                                69  Rhône                   28712 24148         7821
                                73  Savoie                  10624 8257          2357

In [22]:
# Question 2

meilleur_region = ""

with open(fichier_artisans, 'r') as f:
    for ligne in range(nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, 1).value
        if ligne == index_meilleur_alimentation+3:
            meilleur_region = valeur
            break
print("Meilleur régions : " + meilleur_region)

with open(fichier_artisans, 'r') as f:
    for ligne in range(nombre_de_lignes):
        valeur = s.sheets()[0].cell(ligne, 3).value
        print(valeur)

Meilleur régions : Île-de-France



Guadeloupe
Martinique
Guyane
La Réunion
Paris
Seine-et-Marne
Yvelines
Essonne
Hauts-de-Seine
Seine-Saint-Denis
Val-de-Marne
Val-d'Oise
Ardennes
Aube
Marne
Haute-Marne
Aisne
Oise
Somme
Eure
Seine-Maritime
Cher
Eure-et-Loir
Indre
Indre-et-Loire
Loir-et-Cher
Loiret
Calvados
Manche
Orne
Côte-d'Or
Nièvre
Saône-et-Loire
Yonne
Nord
Pas-de-Calais
Meurthe-et-Moselle
Meuse
Moselle
Vosges
Bas-Rhin
Haut-Rhin
Doubs
Jura
Haute-Saône
Territoire de Belfort
Loire-Atlantique
Maine-et-Loire
Mayenne
Sarthe
Vendée
Côtes-d'Armor
Finistère
Ille-et-Vilaine
Morbihan
Charente
Charente-Maritime
Deux-Sèvres
Vienne
Dordogne
Gironde
Landes
Lot-et-Garonne
Pyrénées-Atlantiques
Ariège
Aveyron
Haute-Garonne
Gers
Lot
Hautes-Pyrénées
Tarn
Tarn-et-Garonne
Corrèze
Creuse
Haute-Vienne
Ain
Ardèche
Drôme
Isère
Loire
Rhône
Savoie
Haute-Savoie
Allier
Cantal
Haute-Loire
Puy-de-Dôme
Aude
Gard
Hérault
Lozère
Pyrénées-Orientales
Alpes-de-Haute-Provence
Hautes-Alpes
Alpes-Maritimes
Bouches-du-Rhône
Var
Vaucluse
Corse-du-Sud
Haute-Corse

In [ ]:
"Patience et longueur de temps font plus que force ni que rage", Jean de La Fontaine

In [26]:
dt2 = pd.read_excel(fichier_artisans, sheetname = 'CA + VA', header = 0)
dt2

,Activité artisanale en 2010 (en millier d'euros),Unnamed: 1,Unnamed: 2,Unnamed: 3,chiffre d'affaires,Valeur ajoutée
0,1.0,Guadeloupe,971,Guadeloupe,1442724.03,447836.16
1,2.0,Martinique,972,Martinique,1179135.30,411015.00
2,3.0,Guyane,973,Guyane,673351.58,212134.01
3,4.0,La Réunion,974,La Réunion,2658120.22,917440.43
4,11.0,Île-de-France,75,Paris,10366280.54,4119777.39
5,NaN,NaN,77,Seine-et-Marne,5260904.38,1967502.32
6,NaN,NaN,78,Yvelines,5233207.96,1883047.84
7,NaN,NaN,91,Essonne,4150301.98,1604591.08
8,NaN,NaN,92,Hauts-de-Seine,4261560.55,1712655.51
9,NaN,NaN,93,Seine-Saint-Denis,4906761.22,1859847.41
10,NaN,NaN,94,Val-de-Marne,4342048.09,1693719.47
11,NaN,NaN,95,Val-d'Oise,4033382.77,1632223.74
12,21.0,Champagne-Ardenne,8,Ardennes,991671.04,390856.40
13,NaN,NaN,10,Aube,1049730.36,413827.01
14,NaN,NaN,51,Marne,1664315.93,685930.54
15,NaN,NaN,52,Haute-Marne,673416.16,270639.01
16,22.0,Picardie,2,Aisne,1481264.09,622100.61
17,NaN,NaN,60,Oise,2504897.90,1008834.25
18,NaN,NaN,80,Somme,1845071.76,735816.00
19,23.0,Haute-Normandie,27,Eure,2166339.99,860666.28
20,NaN,NaN,76,Seine-Maritime,4041147.20,1638357.61
21,24.0,Centre,18,Cher,1142333.97,460798.43
22,NaN,NaN,28,Eure-et-Loir,1632368.37,623252.75
23,NaN,NaN,36,Indre,853884.60,349021.84
24,NaN,NaN,37,Indre-et-Loire,2405071.36,933540.84
25,NaN,NaN,41,Loir-et-Cher,1267146.17,512809.54
26,NaN,NaN,45,Loiret,2276119.98,912830.12
27,25.0,Basse-Normandie,14,Calvados,3519035.93,1266574.64
28,NaN,NaN,50,Manche,2110129.88,803564.62
29,NaN,NaN,61,Orne,1047384.40,427280.58
...,...,...,...,...,...,...
70,NaN,NaN,81,Tarn,1879476.71,697159.21
71,NaN,NaN,82,Tarn-et-Garonne,1034742.96,368613.01
72,74.0,Limousin,19,Corrèze,1185001.84,435892.99
73,NaN,NaN,23,Creuse,491772.81,189077.14
74,NaN,NaN,87,Haute-Vienne,1301517.16,498036.87
75,82.0,Rhône-Alpes,1,Ain,3733454.28,1337400.97
76,NaN,NaN,7,Ardèche,1282666.51,492721.68
77,NaN,NaN,26,Drôme,2655708.92,946779.06
78,NaN,NaN,38,Isère,5793911.25,2165347.62
79,NaN,NaN,42,Loire,3642852.71,1393111.32
80,NaN,NaN,69,Rhône,7833304.31,2995306.89
81,NaN,NaN,73,Savoie,2891000.63,1024584.14
82,NaN,NaN,74,Haute-Savoie,3941344.61,1535760.26
83,83.0,Auvergne,3,Allier,1077385.52,446607.30
84,NaN,NaN,15,Cantal,694106.07,254435.45
85,NaN,NaN,43,Haute-Loire,1197115.53,429409.70
86,NaN,NaN,63,Puy-de-Dôme,2446865.19,933521.19
87,91.0,Languedoc-Roussillon,11,Aude,1130454.04,449428.04
88,NaN,NaN,30,Gard,2652020.97,998446.26
89,NaN,NaN,34,Hérault,4112722.36,1523725.54
90,NaN,NaN,48,Lozère,382011.20,149263.25
91,NaN,NaN,66,Pyrénées-Orientales,1753712.18,666474.88
92,93.0,Provence-Alpes-Côte d'Azur,4,Alpes-de-Haute-Provence,893614.49,328564.69
93,NaN,NaN,5,Hautes-Alpes,625819.14,247288.07
94,NaN,NaN,6,Alpes-Maritimes,4986488.09,1974948.51
95,NaN,NaN,13,Bouches-du-Rhône,7443281.14,2739255.62
96,NaN,NaN,83,Var,4218998.16,1640971.82
97,NaN,NaN,84,Vaucluse,2571747.91,959501.47
98,94.0,Corse,2A,Corse-du-Sud,957060.26,369925.84
99,NaN,NaN,2B,Haute-Corse,1001007.55,346351.83

In [65]:
valeursVA =[]
with open(fichier_artisans, 'r') as p:
    for ligne in range(3, nombre_de_lignes):
        val = s.sheet_by_index(1).cell(ligne,5).value
        valeursVA.append(val)
meilleur_department = max(valeursVA)
print(meilleur_department)

IndexError: list index out of range

In [55]:
valeursVA =[]

for line in range(1, nombre_de_lignes):
    valeursVA.append(dt2.get_value(line, 'Valeur ajoutée'))
meilleur_department = max(valeursVA)
meilleur_department

KeyError: 100

In [127]:
valeursVA =[]

index_meilleur_valeurs = []

xl_sheet = s.sheet_by_index(1)
print ('Sheet name: %s' % xl_sheet.name)

with open(fichier_artisans, 'r') as p:
    for ligne in range(1, nombre_de_lignes-2):
        val = s.sheet_by_index(1).cell(ligne,5).value
        valeursVA.append(val)
        
valeursVA.sort(reverse = True)

for line in range(0, 3):
    index_meilleur_valeurs.append(valeursVA[line])
print(index_meilleur_valeurs)
    
with open(fichier_artisans, 'r') as p:
    for ligne in range(1, nombre_de_lignes-2):
        val = s.sheet_by_index(1).cell(ligne,5).value
        if val == index_meilleur_valeurs[0]:
            ville_1 = s.sheet_by_index(1).cell(ligne,3).value
            print(ville_1)
        if val == index_meilleur_valeurs[1]:
            ville_2 = s.sheet_by_index(1).cell(ligne,3).value
            print(ville_2)
        if val == index_meilleur_valeurs[2]:
            ville_3 = s.sheet_by_index(1).cell(ligne,3).value
            print(ville_3)

Sheet name: CA + VA
[4119777.39, 2995306.89, 2819349.89]
Paris
Nord
Rhône